### ISSUE TITLE
Hide UI Option to Submit Schema on non-Pantheon Environments

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#103]
The `SolrPower_Api->submit_schema()` method has some hardcoded dependencies on Pantheon, which makes it very difficult to use in other environments. We should decouple it from the Pantheon environment dependency.

**Comment by allan23** [comment]
@danielbachhuber Can you elaborate on this issue? The submit_schema() method is only for Pantheon and is not an option on non-Pantheon environments. I don't foresee any other environment allowing the ability to send the schema.xml to the Solr instance.

When you say decouple it, are you saying to remove this method completely from the plugin? And if so, does that mean that Pantheon should have separate functionality only on their platform?

I mean it can be done (maybe add some hooks to the options page for Pantheon specific features), just need some clarification on this because it was a must-have feature for this project.

(CC: @joshkoenig  @ataylorme)

**Comment by danielbachhuber** [comment]
> Can you elaborate on this issue? The submit_schema() method is only for Pantheon and is not an option on non-Pantheon environments. I don't foresee any other environment allowing the ability to send the schema.xml to the Solr instance.

Ok, I wasn't aware of this. Should we hide the UI in a non-Pantheon environment then?

> When you say decouple it, are you saying to remove this method completely from the plugin? And if so, does that mean that Pantheon should have separate functionality only on their platform?

Not necessarily. More so, I saw it as a hardcoded dependency on Pantheon that would benefit from some form of abstraction. Given the detail you've provided, I think it would be fine to just hide the UI in a non-Pantheon environment.

**Comment by ataylorme** [comment]
>  just hide the UI in a non-Pantheon environment.
+1 for this - should be a simple change.
