### ISSUE TITLE
Supported Versions of Solr

### ISSUE THREAD

**Issue by kshaner** [pantheon-systems/solr-power#142]
Is there a list of officially supported versions of Solr?  When attempting to use v5.5 or v6.2 I get a 404 error with the ping endpoint.  However, when using the 3.6.2 as provided in the bootstrap bash script it works.

However, in issue #111 it mentions that Pantheon uses the 5.5.x line.  Are there updated instructions for getting setup with newer versions of Solr?

**Comment by ataylorme** [comment]
@kshaner,
Sorry, #111 was incorrect (and why I closed it). We are working on an upgrade path but it is still in the early stages. Solr Power won't work with `5.x` or above due to Solr Power using `schema.xml` vs the Schema API [introduced in `5.0.0`](http://lucene.apache.org/solr/5_0_0/changes/Changes.html#v5.0.0.new_features)

**Comment by kshaner** [comment]
@ataylorme thanks.  This info might be useful in the readme.
