### ISSUE TITLE
Keyword search in Custom Fields

### ISSUE THREAD

**Issue by rdanamcd** [pantheon-systems/solr-power#294]
I would like to duplicate a keyword search in custom fields if possible. Search for "foo bar" and will find a meta_value containing "At a bar".

In wp_query this is not possible. To do this you would have to include a meta_key twice in the query:
`args = array(
   'meta_query' => array(
          'relation' => 'OR',
          array(
               'key' => 'metakey1',
               'value' => 'foo',
               'compare' => 'LIKE'
          ),
          array(
               'key' => 'metakey1', // Same key
               'value' => 'bar',
               'compare' => 'LIKE'
          )
  )
);`
If wp_query allowed the same meta_key twice, then it should find a POST with Custom Field 'metakey1' and value 'At a bar'.

'IN' won't work because 'At a bar' is not IN ( 'foo', 'bar' )

Finally my question. Will the Solr Search plugin parse the above "args" and allow searching using LIKE with the same meta_key twice?

Thanks for your time
Dana

**Comment by danielbachhuber** [comment]
Hi @rdanamcd:

> Will the Solr Search plugin parse the above "args" and allow searching using LIKE with the same meta_key twice?

It's hard to say without being able to test and reproduce. Generally though, Solr Power follows WordPress core behavior. If something is possible with WordPress core, then we can replicate the behavior in Solr Power. Otherwise, it's likely outside scope of the plugin.

> If wp_query allowed the same meta_key twice, then it should find a POST with Custom Field 'metakey1' and value 'At a bar'.

Have you considered opening a core Trac ticket about this? It seems like the underlying change would be relatively simple, as long as there weren't any backwards compatibility concerns.

**Comment by rdanamcd** [comment]
Thanks. I've worked around not needing to search the same meta-key twice in one query.

Appreciate it.
