### ISSUE TITLE
Indexing via WP Cron run

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/solr-power#304]
It would be great if there is a config option to enable index along with WP-Cron run

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @eabquina.

This is an interesting idea — can you share more about the intended use-case? Solr Power currently indexes in an "on-demand" manner, meaning a post is added or updated in the index when it's modified in the admin. In what ways does this current behavior not work for your needs?

**Comment by eabquina** [comment]
hi @danielbachhuber  -- thanks for telling that it was actually working as "on-demand"!

the use case is the choice to not make it on-demand, and rather a scheduled way for a user think necessary. It could be such a busy site (a lot of editors, multiple authors etc,) that this could help in some way with performance. 

Also, there will be a case where we want to re-index the whole site, and if it such a huge one, might want to have cron as an option to queue stuff (and even per post type, taxonomy, custom etc,) 

Kind of inspired also with how woocommerce imports were done, and this actually came out of a conversation with a user in the platform. I'm guessing they were planning out the info structure, throughput etc.

**Comment by danielbachhuber** [comment]
> It could be such a busy site (a lot of editors, multiple authors etc,) that this could help in some way with performance.

Hm. I'm not sure this would actually help with performance in a meaningful way. Submitting updated documents to the index isn't a very costly operation and only happens once during the saving process. As a percentage of time associated with the standard WordPress update user experience, submitting a document to the index is quite small.

> Also, there will be a case where we want to re-index the whole site, and if it such a huge one, might want to have cron as an option to queue stuff (and even per post type, taxonomy, custom etc,)

You're welcome to implement this on your own. I'm not sure it makes sense as a part of the plugin because the re-index process can be quite time-consuming and cron web requests can timeout.

If you have WP-CLI access to your site, you can re-index with `wp solr index`
