### ISSUE TITLE
`Index custom fields` setting requires exact matches

### ISSUE THREAD

**Issue by jedkcanderson** [pantheon-systems/solr-power#311]
The `Index custom fields` setting allows users to add keys that should be added to the Solr index by naming the field keys directly.  This works great for simple fields added by ACF and other plugins that contribute additional fields to WordPress.

However, ACF allows for flexible content which contributes fields with keys that contain number, for example: ```programming_flex_content_2_programming_external_links_0_programming_external_link_label```

Given the flexibility of the data modeling, it is infeasible to add all of the possible combinations in the `Index custom fields` setting.

We'd like the ability to add a setting to allow for more flexible key matching.

**Comment by danielbachhuber** [comment]
Replied in https://github.com/pantheon-systems/solr-power/pull/312#issuecomment-322246470

**Comment by jedkcanderson** [comment]
Continuing the discussion started in #312 here.

ACF stores it's extra field data in the meta table using two keys for each piece of data you append.  One of the keys you don't want because it's just the glue that holds things together the value is usually something like `field_82938523`.

ACF supports a concept of a flexible content area where developers set up a list of available data types and authors can mix & match those fields as they see fit for any given page.  That's were the numbers I talk about above are added.  If you add two images, and a coupled video,and a text field you could get keys like:

```my_custom_post_type_content_0_image
my_custom_post_type_content_1_image
my_custom_post_type_content_2_video_group_content_0_video_url
my_custom_post_type_content_2_video_group_content_1_label```

Using a filter to register the field names of these fields is possible, but would require analyzing the data.  Is there a way to only run a filter if we're doing a `solr index`?  Otherwise I'd have to do a database crawl all the time which would slow everything else down.

**Comment by ataylorme** [comment]
> Is there a way to only run a filter if we're doing a `solr index`? 

We have [an action for indexing being finished](https://github.com/pantheon-systems/solr-power/blob/ab406f0d918916f18d3238e9c9fa2ea170d92a69/includes/class-solrpower-sync.php#L652). 

I think we if add an action for indexing start you could hook into that action, do the analysis, add the filters and then remove the filters again in the `solr_power_index_all_finished` action.

What are your thoughts @danielbachhuber?

**Comment by jedkcanderson** [comment]
Thinking about his more, maybe a different hook would make sense.  I'm going to end up querying the database for all of the documents that are being indexed.  That feels like we're duplicating work.

What about adding a filter like `solr_power_should_index` which takes a callback that accepts post data and a field name?  That way I can do my logic inline.

**Comment by danielbachhuber** [comment]
Another idea to throw into the mix: save all of the post meta keys to an option, and the filter this option value onto Solr Power settings.

Here's some non-functioning code to illustrate the idea:

```
// Not sure what the actual action is...
add_action( 'acf_update_post_meta', function( $value, $key ) {
	$fields = get_option( 'spx_post_fields', array() );
	if ( ! in_array( $key, $fields ) ) {
		$fields[] = $key;
		update_option( 'spx_post_fields', $fields );
	}
});
add_filter( 'solr_index_custom_fields', function( $fields ) {
	return array_merge( $fields, get_option( 'spx_post_fields', array() ) );
});
```

I still think always filtering `solr_index_custom_fields` is the way to go, because we can ensure that filter will be fired every time we reference the custom fields.

The advantage to storing post meta key names is an option is performance — never need to use a nasty `SELECT DISTINCT` query on the post meta table. Plus, we'll have a minimal number of writes if we only update the option when a new key is present.

**Comment by jedkcanderson** [comment]
Following up on this discussion, we have proven that the above approach can work.  Thanks!

**Comment by jedkcanderson** [comment]
We went down a complicated caching path and then circled back and realized we can solve this much easier if the ```apply_filters( 'solr_index_custom_fields', $plugin_s4wp_settings['s4wp_index_custom_fields']);``` call in `SolrPower_Sync::build_document()` is changed to ```apply_filters( 'solr_index_custom_fields', $plugin_s4wp_settings['s4wp_index_custom_fields'], $post_info->ID );```  I really like this solution because it means we can calculate the _exact_ fields we want indexed.

This filter is also called in `SolrPower_WP_Query::parse_meta_query()` and I don't know enough about the code base to know how that would be used.  I'd be happy to create a pull request for the (relatively small) change, but feel a little sheepish about changing the `SolrPower_WP_Query` class as well.

**Comment by jedkcanderson** [comment]
Would somebody have some time to discuss this with me this coming week?  Sept 17-24?

**Comment by danielbachhuber** [comment]
@jedkcanderson Yep, happy to (just getting back online after vacation).

**Comment by danielbachhuber** [comment]
@jedkcanderson How'd this turn out for you?

**Comment by jedkcanderson** [comment]
@danielbachhuber We got this working, however it requires passing in the post ID when you call `apply_filters( 'solr_index_custom_fields' ...)`.  My question is how is `SolrPower_WP_Query::parse_meta_query()` used elsewhere in the system because the post ID isn't always available.

**Comment by danielbachhuber** [comment]
@jedkcanderson Oh. Although it works for your use case, I'm still not quite sure that passing the post ID to `apply_filters( 'solr_index_custom_fields' ...)` is the correct solution to the problem.

The expectation is for the custom fields in the index to be _global across the entire system_, not customizable on a post-by-post basis. The latter implies the keys can vary between posts and doesn't enforce a global naming scheme. If you used key `date` with different meanings on different post types, it could lead to unexpected querying results.

> My question is how is `SolrPower_WP_Query::parse_meta_query()` used elsewhere in the system because the post ID isn't always available.

The post ID won't ever be available in this case because `::parse_meta_query()` is used to query a _collection_ of posts and runs before the post collection is known.

I'd encourage you to follow the original example I suggested (storing the meta keys in an option). Aside from implementation details, it's the architecturally-sound approach.

**Comment by elliottpost** [comment]
I wanted to follow-up on @danielbachhuber's suggestion above.

> ```
> // Not sure what the actual action is...
> add_action( 'acf_update_post_meta', function( $value, $key ) {
> 	$fields = get_option( 'spx_post_fields', array() );
> 	if ( ! in_array( $key, $fields ) ) {
> 		$fields[] = $key;
> 		update_option( 'spx_post_fields', $fields );
> 	}
> });
> add_filter( 'solr_index_custom_fields', function( $fields ) {
> 	return array_merge( $fields, get_option( 'spx_post_fields', array() ) );
> });
> ```

The action here is probably `acf/save_post`, however, the limitation exists such that at this point the fields for ACF are something like `$_POST['acf']['field_123456789abcdef`] = "your value"`, but in the database the meta key is named something similar to `{page_builder}_{x}_{field_name}`, where `{page_builder}` is the name of your ACF group that allows the user to add rows/sections/etc to the post, `{x}` is the row/section number (starting at 0->n), and `{field_name}` is the human friendly field name for `field_123456789abcdef`. 

The challenge, then, is how do you go from the ACF fields in POST to the meta key names that ACF uses? ACF uses `acf_update_value()` to do this process and you may be able to dig through that to determine it, or there may be an easier way I'm not seeing to convert between post object name and meta key. One way that _does_ work is by using `acf/save_post` action with a priority greater than 10 such that your function/method runs after ACF saves the values. From here, you could simply get all the ACF fields that match that particular post, and merge them into the option that Daniel suggested.

something like... (this is non-functional but should get you close)
```php
add_action('acf/save_post', function($post_id) {
   $meta_keys = get_post_meta($post_id);
   if (!$meta_keys) return $post_id;

   // get a list of the ACF keys you want to index
   $acf_meta_keys =[];
   // probably make this sub-piece a method for recursing through nested acf fields
   foreach ($meta_keys as $key => $val_arr) {
      if (strpos($key, "page_builder") === 0)) $acf_meta_keys[] = $key;

      // handle recursion here...
   }

  // update the option
  $existing_known_fields = get_option('my_solr_index_acf_fields', []);
  update_option('my_solr_index_acf_fields', array_unique($existing_known_fields, $acf_meta_keys), false);

  return $post_id;
});
```

Additionally, you can improve the above method with some whitelisting if you only want solr to index specific ACF fields. Just improve the filtering.

For us, because our database is small, we solved this issue using the dreaded "SELECT DISTINCT" query since this happens only every time the index is built, which is already a slow action.

Our solution code is:

```php
add_filter('solr_index_custom_fields',
    function($custom_fields) {
        // get all wysiwyg items from page builder tool
        global $wpdb;

        $wysiwyg_fields = get_transient('solr_index_acf_fields');
        if (empty($wysiwyg_fields)) {
            $wysiwyg_fields = $wpdb->get_col("SELECT DISTINCT meta_key FROM {$wpdb->postmeta} WHERE meta_key LIKE 'page_builder_%_wysiwyg_content'");
            set_transient('solr_index_acf_fields', $wysiwyg_fields, 60*60*24);
        }

        return array_merge($custom_fields, $wysiwyg_fields);
    }
    10, 1
);
```

The last snippet works. You should add it to your code where you hook into the other solr functionality.

See: https://www.advancedcustomfields.com/resources/acf-save_post/
