### ISSUE TITLE
Is WPML compatible with Pantheon Solr

### ISSUE THREAD

**Issue by aaman** [pantheon-systems/solr-power#381]
Hi,

I have a Wordpress website that is built using ACF and WPML for translations between English and French.  I installed the Pantheon Solr plugin and it is able to index my posts and pages for English but it is not able to index my French pages?

Is there an additional configuration that I have to add or is WPML not supported?

**Comment by ataylorme** [comment]
Hi @aaman,
I don't have much experience with WPML but according to their documentation the WPML plugin [stores translation data in a custom database table](https://wpml.org/documentation/support/wpml-tables/). 

Unfortunately, because the translations are stored in a custom database table, outside of the normal WordPress data storage, it is out of scope for the Solr Power plugin.

Solr Power only supports WordPress default data storage (custom post types, meta data, taxonomies, etc.).

It may be possible to get the data into Solr but you would need to work with Solr directly as the Solr Power plugin does not handle custom data like this.

The [Solarium library](https://solarium.readthedocs.io/en/master/), which Solr Power is built on top of, will likely be useful. 

Good luck and please let us know if you get it working as we can document the solution for future folks using WPML.

**Comment by aaman** [comment]
Hi @ataylorme thanks for the update
