### ISSUE TITLE
Lazy load server ping check instead of 'init'

### ISSUE THREAD

**Issue by dougaxe1** [pantheon-systems/solr-power#433]
In reviewing New Relic data from a production application using Solr Power I noticed the ping request in every request, while quick, towers over all other requests by frequency:

https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-api.php#L73 
`add_action( 'init', array( $this, 'ping_server' ) );`

It seems like the default behavior should be to only ping on `is_search()` or `is_admin()` (for indexing purposes).

Is this ping request needed on every page request?

**Comment by danielbachhuber** [comment]
Thanks for the issue, @dougaxe1 

> It seems like the default behavior should be to only ping on `is_search()` or `is_admin()` (for indexing purposes).

It looks like there are two instances where the `ping` attribute is checked:
* https://github.com/pantheon-systems/solr-power/blob/e2f133c257058beb4426e819ee5ed98e17df0c54/includes/class-solrpower-wp-query.php#L141-L142
* https://github.com/pantheon-systems/solr-power/blob/e2f133c257058beb4426e819ee5ed98e17df0c54/includes/class-solrpower-wp-query.php#L374

One of the instances allows for any use of `get_query_var( 'solr_integrate' )`, so it wouldn't be safe to limit it to `is_search()` and `is_admin()`.

However, we could probably lazy load the check instead.

> I noticed the ping request in every request, while quick, towers over all other requests by frequency:

Out of curiosity, how long does the ping request take? Is this a Pantheon site?

**Comment by dougaxe1** [comment]
This site is on Pantheon and the check is relatively fast, ~20ms. It was the frequency which alerted me to its presence.

**Comment by danielbachhuber** [comment]
Ok. I'll look into lazy loading the check when I have some time.

**Comment by fakingfantastic** [comment]
Hey @danielbachhuber , just wanted to mention an issue that I believe #458 caused for me (but it could be due to my limited knowledge of the plugin).

When we updated from 2.1.3 -> 2.2.1, our custom Solr queries stopped working.

We originally had setup code like this...
```php
        $this->solrApi = SolrPower_Api::get_instance();
        $this->solrClient = $this->solrApi->solr;
        $this->helper = $this->solrClient->createSelect()->getHelper();
```

.. and started getting this error
> Fatal error: Uncaught Error: Call to a member function createSelect() on null


We fixed it by adding a quick ping before running the query
```php
        $this->solrApi = SolrPower_Api::get_instance();
        get_solr()->ping(get_solr()->createPing());
        $this->solrClient = $this->solrApi->solr;
        $this->helper = $this->solrClient->createSelect()->getHelper();
```

Let me know if my solution is right, if there's a better way to do it, or if it is a bug that you need more input from me to help to patch.

Thanks ✌️

**Comment by danielbachhuber** [comment]
@fakingfantastic Sorry about that! I didn't think about that scenario when I implemented it.

Your proposed solution seems just fine. An alternative, which would accommodate a failed response from Solr, could be:

```php
if ( ! SolrPower_Api::get_instance()->ping ) {
	return; // Or throw an exception or whatever.
}
$this->solrApi = SolrPower_Api::get_instance();
$this->solrClient = $this->solrApi->solr;
$this->helper = $this->solrClient->createSelect()->getHelper();
```

I don't think we'll revert #458 at this point because we'd still like to avoid pinging Solr until we need it.

Hope this helps!
