### ISSUE TITLE
How is it possible to change the page result limit from 10 to higher value?

### ISSUE THREAD

**Issue by albertcausing** [pantheon-systems/solr-power#76]
Even manipulated to sets to 100 from the config page https://monosnap.com/file/bM3fyHDdaB8XyJsGurHawwpW0Z8R04
or using this file includes/class-solrpower-options.php

Is there a way to increase result value from 10?

**Comment by ataylorme** [comment]
@albertcausing I don't believe this is an issue with the Solr Power plugin. The Solr Power plugin replaces `WP_Query` results with items from Solr instead of the database but makes no other changes. 

If you (or your theme or one of your plugins) are using [the pagination parameters of WP_Query](https://codex.wordpress.org/Class_Reference/WP_Query#Pagination_Parameters), settings the number of results to 10, for example, then the value in the WordPress dashboard is overwritten.

Can you check your code or with the author of your theme (or wherever you are seeing the issue on the front-end of the site)?

**Comment by ataylorme** [comment]
@albertcausing Were you able to test on your end to adjust `WP_Query` parameters?

**Comment by ataylorme** [comment]
Closing this out since there hasn't been activity in months.
